### ISSUE TITLE
MaAlpsのGHワークフロー化

### ISSUE THREAD

**Issue by koriym** [ma-alps/MaAlps.MaAlps#26]
GH Actionは[ワークフロー データを成果物として保存する事ができます。](https://docs.github.com/ja/actions/advanced-guides/storing-workflow-data-as-artifacts) という事からインスプレーションを受けました。

この機能を使ってALPSプロファイルをcommitすればワークフロー内で生成された、ASDダイアグラムとHTML一式をアップロードする事ができます。つまり、MaAlpsのASD作成機能はGH Actionのワークフローで代替可能ではないでしょうか？

## milestone 0

1. ユーザーがGHワークフローを設定してcommit
2. GHワークフローでASDを生成されアップロードされる

ユーザーはGHのワークフローのページから生成物一式をダウンロードできローカルで見る事ができます。

まずはここまでの作成
ここまではMaAlpsは登場しません。ユーザーがローカルに環境を用意しないでGHへのpushだけで、ASD生成物がダウンロードができます。

## milestone 1

3. ワークフローから通知を受け取ったMaAlpsが**アップロードされたファイルをダウンロードして**HTMLホスティング
4. ユーザーに紐付け、その他

## 例

これはphp metricsのツールの出力をアップロードされた例です。

https://github.com/ma-alps/MaAlps.MaAlps/actions/runs/1465422685

HTML Reportのリンクでダウンロードできます。

<img src="https://user-images.githubusercontent.com/529021/141926917-3adbf380-30fa-4321-a9ff-f71f06fb942c.png" width="50%">

アップロードは[actions/upload-artifact@v1](https://github.com/actions/upload-artifact)というアクションで実現されています。
https://github.com/ma-alps/MaAlps.MaAlps/actions/runs/1465422685/workflow#L22

これをdownloadするアクション
https://github.com/actions/download-artifact

**Comment by koriym** [comment]
GH pagesにアップロードする事もできるようです。

https://qiita.com/peaceiris/items/d401f2e5724fdcb0759d

**Comment by h13** [comment]
めちゃ良いですね。 Ma だと思いました。笑
成果物はあくまでスキーマ、まで洗練させられますね。

**Comment by koriym** [comment]
実装しました。
https://github.com/koriym/asd-action

**Comment by koriym** [comment]
リリースしました！🎉
https://github.com/marketplace/actions/app-state-diagram

**Comment by koriym** [comment]
テンプレートレポジトリも作成しました🎉
https://github.com/koriym/alps-skeleton

**Comment by koriym** [comment]
試してみてください。


1. https://github.com/koriym/alps-skeleton
から下のボタンで自分のレポジトリに作成します。
<img src="https://user-images.githubusercontent.com/529021/141998904-13ff5082-53d3-4601-bae0-0a63d59e57fa.png" width="20%">

2. [GitHub Pages サイトの公開元を設定](https://docs.github.com/ja/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)します。

これでASDサイトが生成され、commitする度にCIでアップデートされます。
公開URLは表示されますが以下のようになります。

https://{user}.github.io/{repository}/
https://koriym.github.io/skeleton-test/

**Comment by koriym** [comment]
`milestone 0`として提示したものは完成しました。

`milestone 1`として提示したものは速度面やプライベートのものを考えるとあまり良いアイデアではないと思います。
